version: "3.7"

services:
  react:
    container_name: react-books
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/app'
      - '/app/node_modules'
    ports:
      - '8081:3000'
