version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn django_books.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - dmp_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  react:
    build:
      context: ../react-books
      dockerfile: Dockerfile.prod
    volumes:
      - react_build:/app/build
    depends_on:
      - web
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
      - react_build:/app/build
    depends_on:
      - web
      - react

volumes:
  dmp_postgres_data:
  static_volume:
  media_volume:
  react_build: