version: "3.7"

services:
  web:
    build: ./
    command: bash -c "python /src/books/backend/manage.py migrate --noinput &&
      python /src/books/backend/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - books_postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

volumes:
  books_postgres_data:
