# Generated by Django 3.2 on 2021-04-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='Дарья Урусова', max_length=255),
        ),
    ]
