# Generated by Django 3.1.8 on 2021-04-23 03:31

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile', validators=[store.models.file_size], verbose_name='Аватар'),
        ),
    ]
