# Generated by Django 3.1.8 on 2021-04-26 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210423_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mini_poster',
            field=models.ImageField(default='chapter', upload_to='book_mini/', verbose_name='Миниатюра-обложки'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.TextField(blank=True, verbose_name='Глава')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book')),
            ],
        ),
    ]
