# Generated by Django 3.1.8 on 2021-04-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210426_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapters',
            options={'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Аватар'},
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='Описание', max_length=2000, verbose_name='Описание'),
        ),
    ]
